- name: Install base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    use: apt
  with_items: "{{ base_packages }}"

- name: Add Google cloud sign key
  ansible.builtin.apt_key:
    url: "{{ google_cloud_public_sign_key_url }}"
    keyring: "{{ google_cloud_public_sign_key_path }}"

- name: Add Kubernetes repo
  ansible.builtin.apt_repository:
    repo: "{{ kubernetes_repo }}"
    filename: kubernetes

- name: Update and upgrade installed packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: safe

- name: Install k8s packages
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ k8s_packages }}"

- name: Populate containerd config.toml
  ansible.builtin.command: containerd config default > /etc/containerd/config.toml

- name: Configure containerd cgroup driver
  ansible.builtin.command: sudo sed -i 's/            SystemdCgroup = false/            SystemdCgroup = true/' /etc/containerd/config.toml
  notify: 
    - Restart containerd

- name: Forwarding IPv4
  ansible.builtin.command:
    cmd: |
      cat <<EOF | tee /etc/modules-load.d/k8s.conf
      overlay
      br_netfilter
      EOF
  notify:
    - Modprobe overlay
    - Modprobe br_netfilter


- name: letting iptables see bridged traffic
  ansible.builtin.command:
    cmd: |
      cat <<EOF | tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      EOF
  notify:
    - Apply sysctl params

- name: Disable swap
  ansible.builtin.command: swapoff -a; sed -i '/swap/d' /etc/fstab
